"""add soft delete fields

Revision ID: add_soft_delete_fields_2
Revises: ca551b1cd312
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_soft_delete_fields_2'
down_revision: Union[str, None] = 'ca551b1cd312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_and_roles', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users_and_roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users_and_roles', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('users_and_roles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_and_roles_deleted_by_users', 'users_and_roles', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_and_roles_created_by_users', 'users_and_roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_and_roles_created_by_users', 'users_and_roles', type_='foreignkey')
    op.drop_constraint('fk_users_and_roles_deleted_by_users', 'users_and_roles', type_='foreignkey')
    op.drop_column('users_and_roles', 'created_by')
    op.drop_column('users_and_roles', 'deleted_by')
    op.drop_column('users_and_roles', 'deleted_at')
    op.drop_column('users_and_roles', 'is_deleted')
    # ### end Alembic commands ### 